# Site settings
title: Watir.us
tagline: Webdriver made easy
header-img: img/11.jpg
email: carldmitch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  'Watir us' is a place for me to share what I've learned while
  automating testing with Ruby and Selenium Webdriver.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://watir.us" # the base hostname & protocol for your site
twitter_username: carldmitch
github_username:  carldmitch

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
